# k8s/import-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: dblp-import-job
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure

      containers:
      - name: importer
        image: advdaba_import:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app
        # Tell the wrapper exactly where the JSON lives on the host
        args: ["/data/dblpv14.json"]
        envFrom:
          - configMapRef:
              name: import-config
          - secretRef:
              name: neo4j-creds
        volumeMounts:
          - name: import-data
            mountPath: /data
        resources:
          limits:
            memory: "3Gi"
          requests:
            memory: "1Gi"

      volumes:
      - name: import-data
        hostPath:
          # On Docker Desktop, your D: drive is under /host_mnt/d
          path: /host_mnt/d/Users/antho/Sem1/TP02/import
          type: Directory
