apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.14.0
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              value: "neo4j/testtest"
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: dblp-volume
              mountPath: /imports
      volumes:
        - name: config
          configMap:
            name: neo4j-config
        - name: dblp-volume
          hostPath:
            path: /run/desktop/mnt/host/d/Users/antho/Sem1/TP02/import
            type: Directory
